services:
  - type: web
    name: shopnest-next
    env: node
    rootDir: shopnest-next
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
